# Generated by Django 2.2.4 on 2019-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contractor',
            field=models.CharField(default='MYZ', max_length=500),
        ),
    ]
