# Generated by Django 2.2.4 on 2019-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contractor',
            field=models.CharField(choices=[('ABCI', 'ABC Inc.'), ('MYZ', 'MYZ Inc.'), ('ACORN', 'Acorn Construction')], max_length=500),
        ),
    ]
