# Generated by Django 2.2.4 on 2019-08-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='destination',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='odo_end',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='odo_start',
            field=models.IntegerField(blank=True),
        ),
    ]
