# Generated by Django 2.0.5 on 2019-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reimbursement_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
