# Generated by Django 2.0.5 on 2019-08-11 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_reimbursement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='week_end',
            field=models.DateField(default=datetime.date(2019, 8, 11), verbose_name='End of week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='week_start',
            field=models.DateField(default=datetime.date(2019, 8, 11), verbose_name='Start of week'),
            preserve_default=False,
        ),
    ]
