# Generated by Django 2.0.5 on 2019-08-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190811_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='week_start',
        ),
    ]
