# Generated by Django 2.0.5 on 2019-08-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190811_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='entry_date',
        ),
    ]
