# Generated by Django 2.2.4 on 2019-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190924_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreappsettings',
            name='reimbursement_rate',
            field=models.FloatField(default=0.53),
        ),
        migrations.AlterField(
            model_name='coreappsettings',
            name='spreadsheet_email',
            field=models.CharField(default='jacksonfoster444@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(verbose_name='Date of entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(verbose_name='Last modified'),
        ),
    ]
