# Generated by Django 2.2.4 on 2019-09-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190925_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='odo_end',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
