# Generated by Django 2.0.5 on 2019-08-11 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190811_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='week_end',
            field=models.DateField(default=datetime.date(2019, 8, 11), verbose_name='Week end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='week_start',
            field=models.DateField(default=datetime.date(2019, 8, 11), verbose_name='Week start'),
            preserve_default=False,
        ),
    ]
