# Generated by Django 2.2.4 on 2019-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190929_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreappsettings',
            old_name='spreadsheet_email',
            new_name='abci_send_to_email',
        ),
        migrations.AddField(
            model_name='coreappsettings',
            name='acorn_send_to_email',
            field=models.CharField(default='jacksonfoster444@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='coreappsettings',
            name='myz_send_to_email',
            field=models.CharField(default='jacksonfoster444@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='contractor',
            field=models.CharField(default='MYZ', max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='destination',
            field=models.CharField(max_length=500),
        ),
    ]
