# Generated by Django 2.0.5 on 2019-08-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190811_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreappsettings',
            name='spreadsheet_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
