# Generated by Django 2.2.4 on 2019-10-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191008_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contractor',
        ),
    ]
