# Generated by Django 2.0.5 on 2019-08-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190811_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='week_end',
            new_name='pay_period_end',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='week_start',
            new_name='pay_period_start',
        ),
    ]
