# Generated by Django 2.0.5 on 2019-08-18 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190814_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='reimbursement_rate',
        ),
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 18, 0, 52, 53, 981095), verbose_name='Last modified'),
            preserve_default=False,
        ),
    ]
