# Generated by Django 2.2.4 on 2019-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_entry_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreappsettings',
            name='abci_contact_name',
            field=models.CharField(default='Mel', max_length=255),
        ),
        migrations.AddField(
            model_name='coreappsettings',
            name='acorn_contact_name',
            field=models.CharField(default='Brad', max_length=255),
        ),
        migrations.AddField(
            model_name='coreappsettings',
            name='myz_contact_name',
            field=models.CharField(default='Brad', max_length=255),
        ),
    ]
