# Generated by Django 2.2.4 on 2019-10-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191008_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreappsettings',
            name='cc_email',
            field=models.CharField(default='jackson@jacksonwfoster.com', max_length=255),
        ),
    ]
