# Generated by Django 2.0.5 on 2019-08-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190818_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
