# Generated by Django 2.0.5 on 2019-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entry_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
